spring:
  application:
    name: zipcode
    version: 0.0.1
  cloud:
    config:
      enabled: false
  datasource:
    url: jdbc:postgresql://localhost:${DB_PORT}/mydatabase
    username: myuser
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
cep:
  baseUrl: https://opencep.com/v1

